# This is a basic workflow to help you get started with Actions

name: CI - aircraft-cj4

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build Package
        run: powershell.exe -noexit build.ps1 -Project workingtitle.xml -Package workingtitle-aircraft-cj4
      - name: Upload Package
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: workingtitle-aircraft-cj4
          # A file, directory or wildcard pattern that describes what to upload
          path: build/workingtitle-aircraft-cj4
          if-no-files-found: error
